# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.DateTimeField(verbose_name='Date registered')),
                ('dataA', models.FloatField(default=0)),
                ('dataB', models.FloatField(default=0)),
            ],
        ),
    ]
